# This file was generated by GoReleaser. DO NOT EDIT.
cask "afl" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e995c9496e84f2f0fd304ddcb462f79f97482b3acb710e3e7e684f6d8b64b07e"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd51a32d3d69d9f6143f02db137551b57401c2e6aa9fc62a4199c8e76849e3fd"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1502b96729932da48f1a624ea0de93063dab23a95373f379b08a052eebaba868"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c58704085207bb31894dbea65131d7985dce83fcabe8de37dbd0d39677783dae"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "afl"
  desc "Lock files against coding agents with OS-level immutable flags"
  homepage "https://github.com/Mineru98/agent-file-lock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afl"

  generate_completions_from_executable "afl", "completion",
    base_name: "afl",
    shell_parameter_format: :arg,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Strong locks (chflags schg) need root:
      sudo afl lock -f afl.yaml
    Verifying needs no privileges:
      afl check -f afl.yaml
  EOS
end
