# This file was generated by GoReleaser. DO NOT EDIT.
cask "afl" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "a9be5764fc4253540e996aedf20046a75211457593dee6079da48e993fb6c93b"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2768627e7e694e6515e478eaef5d7865cfa7ccc59af7253a35f389a4850f3cb"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6a0cc6c0d1489a14df11f62e62a393a6393601d5af7d7ac6d5c0b2e290c8f69c"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fbcc068544d4a18a71e587afad96bbad6d23443e74a7475109c2cb46eb6f6bbb"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "afl"
  desc "Lock files against coding agents with OS-level immutable flags"
  homepage "https://github.com/Mineru98/agent-file-lock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afl"
  bash_completion "completions/afl.bash"
  fish_completion "completions/afl.fish"
  zsh_completion "completions/afl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Strong locks (chflags schg) need root:
      sudo afl lock -f afl.yaml
    Verifying needs no privileges:
      afl check -f afl.yaml
  EOS
end
