# This file was generated by GoReleaser. DO NOT EDIT.
cask "afl" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "deec7eb64d24dbaa4b3c917d727c7a3c605bf1071b4dc6e5174007d047e7eac8"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "296f0bfba4425a5a67cb54966a04c09704cc8cd96f8d45e0074a658046f693d5"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c08636239fc0e9e10d49c4cd2b26dbb74f142f3137e43516c7d6acb25cfd645"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4bdc6b1f0010911109d037a4298ebd5fff011f03b3a15c846870fe05b67117e1"
      url "https://github.com/Mineru98/agent-file-lock/releases/download/v#{version}/afl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "afl"
  desc "Lock files against coding agents with OS-level immutable flags"
  homepage "https://github.com/Mineru98/agent-file-lock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "afl"
  bash_completion "completions/afl.bash"
  fish_completion "completions/afl.fish"
  zsh_completion "completions/afl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/afl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Strong locks (chflags schg) need root:
      sudo afl lock -f afl.yaml
    Verifying needs no privileges:
      afl check -f afl.yaml
  EOS
end
